name: 운영서버에 배포

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [ "closed" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest # 작업이 실행될 환경
    steps:
    - name: 체크아웃
      uses: actions/checkout@v3
    - name: JDK 17 사용
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Gradle Wrapper 실행 권한 추가
      run: chmod +x gradlew
    - name: Gradle로 빌드(CI)
      run: ./gradlew build
      env:
        SPRING_CONFIG_LOCATION: src/main/resources/application-server.properties
        DB_URL: ${{ secrets.DB_PROD_URL }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    - name: 도커허브에 로그인
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USER_NAME }}
        password: ${{ secrets.DOCKER_USER_PW }}
    - name: 이미지 빌드
      run: docker build -t ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:prod -f Dockerfile.prod .
    - name: 도커허브에 이미지 푸시
      run: docker push ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:prod
    - name: AWS EC2에 ssh 접속 후 배포
      uses: appleboy/ssh-action@master     
      with:
        host: ${{ secrets.AWS_PROD_IP }}          
        username: ${{ secrets.AWS_USER_NAME }}
        key: ${{ secrets.AWS_KEY }}
        port: 22
        script: |
          docker pull ${{ secrets.DOCKER_USER_NAME }}/${{ secrets.DOCKER_IMAGE_NAME }}:prod
          docker-compose up -d